<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="chrome-debugging-protocol.json" />
    <EmbeddedResource Remove="chrome-debugging-protocol.json" />
    <None Remove="chrome-debugging-protocol.json" />
    <Compile Remove="OutputProtocol\**" />
    <EmbeddedResource Remove="OutputProtocol\**" />
    <None Remove="OutputProtocol\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CSnakes.Runtime" Version="1.0.35" />
    <PackageReference Include="EntryPoint" Version="1.3.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="NJsonSchema.NewtonsoftJson" Version="11.3.2" />
    <PackageReference Include="System.Security.Cryptography.Algorithms" Version="4.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BaristaLabs.ChromeDevTools.Core\BaristaLabs.ChromeDevTools.Core.csproj" />
    <ProjectReference Include="..\BaristaLabs.ChromeDevTools.Core\BaristaLabs.ChromeDevTools.Core.csproj" />
    <ProjectReference Include="..\BaristaLabs.ChromeDevTools.RemoteInterface\BaristaLabs.ChromeDevTools.RemoteInterface.csproj" />
  </ItemGroup>
</Project>